local helpers = require("stuff.open-link.helpers")
local expanders = require("stuff.open-link.expanders")

describe("open-link", function()
  describe("is_http_or_file_link", function()
    it("returns true for http links", function()
      assert.is_true(helpers.is_http_or_file_link("http://example.com"))
      assert.is_true(helpers.is_http_or_file_link("https://example.com"))
    end)

    it("returns true for file links", function()
      assert.is_true(helpers.is_http_or_file_link("file:///home/user/file.txt"))
    end)

    it("returns true for absolute paths", function()
      assert.is_true(helpers.is_http_or_file_link("/usr/local/bin"))
    end)

    it("returns false for other strings", function()
      assert.is_false(helpers.is_http_or_file_link("elentok/stuff.nvim"))
      assert.is_false(helpers.is_http_or_file_link("PROJ-123"))
      assert.is_false(helpers.is_http_or_file_link("relative/path"))
    end)
  end)

  describe("expanders", function()
    describe("github", function()
      it("expands owner/repo to github URL", function()
        assert.equals("https://github.com/elentok/stuff.nvim", expanders.github("elentok/stuff.nvim"))
      end)

      it("expands repos with dots and dashes", function()
        assert.equals("https://github.com/user/my-repo.nvim", expanders.github("user/my-repo.nvim"))
      end)

      it("expands github.com without protocol", function()
        assert.equals("https://github.com/elentok/stuff.nvim", expanders.github("github.com/elentok/stuff.nvim"))
      end)

      it("returns nil for non-matching strings", function()
        assert.is_nil(expanders.github("just-a-word"))
        assert.is_nil(expanders.github("https://example.com"))
        assert.is_nil(expanders.github("a/b/c"))
      end)
    end)

    describe("jira", function()
      it("expands jira issue keys", function()
        local expand = expanders.jira("https://jira.example.com/browse/", { "PROJ", "DEV" })
        assert.equals("https://jira.example.com/browse/PROJ-123", expand("PROJ-123"))
        assert.equals("https://jira.example.com/browse/DEV-456", expand("DEV-456"))
      end)

      it("is case insensitive", function()
        local expand = expanders.jira("https://jira.example.com/browse/", { "PROJ" })
        assert.equals("https://jira.example.com/browse/proj-123", expand("proj-123"))
      end)

      it("returns nil for non-matching strings", function()
        local expand = expanders.jira("https://jira.example.com/browse/", { "PROJ" })
        assert.is_nil(expand("OTHER-123"))
        assert.is_nil(expand("not-a-ticket"))
      end)
    end)

    describe("github_issue_or_pr", function()
      it("expands issue/PR references", function()
        local expand = expanders.github_issue_or_pr("GH", "elentok/stuff.nvim")
        assert.equals("https://github.com/elentok/stuff.nvim/pull/42", expand("GH#42"))
      end)

      it("returns original for non-matching strings", function()
        local expand = expanders.github_issue_or_pr("GH", "elentok/stuff.nvim")
        assert.equals("something-else", expand("something-else"))
      end)
    end)

    describe("homedir", function()
      it("expands ~ to home directory", function()
        local expand = expanders.homedir()
        local home = os.getenv("HOME")
        assert.equals("file://" .. home .. "/Documents/file.txt", expand("~/Documents/file.txt"))
      end)

      it("returns nil for non-home paths", function()
        local expand = expanders.homedir()
        assert.is_nil(expand("/absolute/path"))
        assert.is_nil(expand("relative/path"))
      end)
    end)

    describe("regex", function()
      it("substitutes pattern in link", function()
        local expand = expanders.regex("^foo", "bar")
        assert.equals("bar-baz", expand("foo-baz"))
      end)

      it("returns original when no match", function()
        local expand = expanders.regex("^foo", "bar")
        assert.equals("baz-qux", expand("baz-qux"))
      end)
    end)
  end)
end)
