local config = require("stuff.toggle-word.config")

describe("toggle-word", function()
  describe("config", function()
    it("has values defined as a table", function()
      assert.is_table(config.values)
    end)

    it("contains expected toggle pairs", function()
      assert.equals("false", config.values["true"])
      assert.equals("False", config.values["True"])
      assert.equals("no", config.values["yes"])
      assert.equals("off", config.values["on"])
      assert.equals("disabled", config.values["enabled"])
      assert.equals("disable", config.values["enable"])
      assert.equals("right", config.values["left"])
      assert.equals("bottom", config.values["top"])
      assert.equals("down", config.values["up"])
      assert.equals("light", config.values["dark"])
      assert.equals("let", config.values["const"])
      assert.equals("-", config.values["+"])
    end)

    it("maps CSS directional properties", function()
      assert.equals("border-right", config.values["border-left"])
      assert.equals("border-bottom", config.values["border-top"])
      assert.equals("margin-right", config.values["margin-left"])
      assert.equals("margin-bottom", config.values["margin-top"])
      assert.equals("padding-right", config.values["padding-left"])
      assert.equals("padding-bottom", config.values["padding-top"])
    end)

    it("has a default register", function()
      assert.is_string(config.register)
    end)
  end)
end)
